import time

print(input(str("what is your name?: ")))
print(input(str("what is your credit card information?: ")))
print(input(str("what is your social security number?: ")))
print(input(str("what is your address?: ")))
print(input(str("what is your phone number?: ")))
print(input(str("what is your email address?: ")))
print(input(str("what is your date of birth?: ")))
print(input(str("what is your mother's maiden name?: ")))
print(input(str("what is your favorite color?: ")))
print(input(str("what is your favorite food?: ")))
print(input(str("what is your favorite movie?: ")))
print(input(str("what is your favorite book?: ")))
print(input(str("what is your favorite hobby?: ")))
print(input(str("what is your favorite sport?: ")))
print(input(str("what is your favorite music genre?: ")))
print(input(str("what is your favorite band?: ")))
print(input(str("what is your favorite song?: ")))
print(input(str("what is your favorite vacation spot?: ")))
print(input(str("what is your google password?: ")))
print(input(str("what is your facebook password?: ")))
print(input(str("what is your instagram password?: ")))
print(input(str("what is your twitter password?: ")))
print(input(str("what is your snapchat password?: ")))
print(input(str("what is your linkedin password?: ")))
print(input(str("what is your amazon password?: ")))
print(input(str("what is your apple id password?: ")))
print(input(str("what is your netflix password?: ")))
print(input(str("what is your spotify password?: ")))
print(input(str("what is your bank account password?: ")))
print(input(str("what is your paypal password?: ")))
print(input(str("what is your venmo password?: ")))
print(input(str("what is your cash app password?: ")))
print(input(str("what is your zelle password?: ")))
print(input(str("what is your wifi password?: ")))
print(input(str("what is your router password?: ")))
print(input(str("what is your computer password?: ")))
print(input(str("what is your phone password?: ")))
print(input(str("what is your tablet password?: ")))
print(input(str("what is your gaming console password?: ")))
print(input(str("what is your email password?: ")))
print(input(str("what is your work email password?: ")))
print(input(str("what is your school email password?: ")))
print("sending to hacker . ")
time.sleep(1)


print("sending to hacker. .")
time.sleep(1)
print("sending to hacker. . .")
time.sleep(1)
print("sent to hacker")
time.sleep(2)
print("just kidding!! this was a prank :)")
